name: Build and Deploy to Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm
          cache-dependency-path: site/package-lock.json

      - name: Install
        working-directory: site
        run: npm ci || npm install

      - name: Build (custom domain)
        working-directory: site
        run: npm run build

      - name: Add CNAME
        run: echo www.oceanicai.org > site/dist/CNAME

      - name: Inject canonical tags
        shell: pwsh
        run: |
          $origin  = 'https://www.oceanicai.org'
          $dist    = 'site/dist'
          $distAbs = (Resolve-Path $dist).Path

          # Normalize a relative URL for each index.html
          Get-ChildItem -Path $distAbs -Filter index.html -Recurse | ForEach-Object {
            $file = $_.FullName
            $dir  = Split-Path -Path $file -Parent

            # Cross-platform relative path, then turn \ into /, and ensure leading slash when present
            $rel  = [System.IO.Path]::GetRelativePath($distAbs, $dir)
            $rel  = $rel -replace '\\','/'
            if ([string]::IsNullOrWhiteSpace($rel)) { $url = "$origin/" } else { $url = "$origin/$rel/" }

            $html = Get-Content -Raw -Path $file

            # Only inject if not present
            if ($html -notmatch '(?i)<link[^>]+rel\s*=\s*["'']canonical["'']') {
              $tag = "<link rel=`"canonical`" href=`"$url`" />"

              # Prefer insert AFTER <head ...>
              if ($html -match '(?is)(<head[^>]*>)') {
                $new = $html -replace '(?is)(<head[^>]*>)', "`$1`n  $tag"
              } else {
                # Fallback: before first </head> if somehow missing opening tag
                $new = $html -replace '(?is)</head>', "  $tag`n</head>"
              }

              [System.IO.File]::WriteAllText($file, $new, [System.Text.UTF8Encoding]::new($false))
              Write-Host "Injected canonical $url -> $file"
            } else {
              Write-Host "Canonical already present -> $file"
            }
          }

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4